CREATE TABLE 'Game'{
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
    NameGame VARCHAR(25);
    ID_Team INTEGER;
}

CREATE TABLE 'Team'{
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
    Game VARCHAR(25);
    Name VARCHAR(25);
}

CREATE TABLE 'Osu_team'{
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
    NameTeam VARCHAR(25);
    ID_member INTEGER;
    TotalMatch INTEGER;
    Win INTEGER;
    Lose INTEGER;
    Equal INTEGER;

}

